name: train
run_id: commands[0]
env COMSPEC: C:\Windows\system32\cmd.exe
env NUMBER_OF_PROCESSORS: 8
env PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
env PROCESSOR_ARCHITECTURE: AMD64
env PROGRAMDATA: C:\ProgramData
env PROGRAMFILES: C:\Program Files
env PROGRAMFILES(X86): C:\Program Files (x86)
env SYSTEMDRIVE: C:
env SYSTEMROOT: C:\Windows
env TEMP: C:\Users\DELL\AppData\Local\Temp
env TMP: C:\Users\DELL\AppData\Local\Temp
env USERPROFILE: C:\Users\DELL
env LANG: en_US.UTF-8
env PATH: C:\Users\DELL\Desktop\titanic-assignment\.tox\test_package\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;%NVM_HOME%;%NVM_SYMLINK%;C:\Python310\Scripts\;C:\Python310\;C:\Users\DELL\AppData\Local\Microsoft\WindowsApps;C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\DELL\AppData\Roaming\npm;C:\ProgramData\nvm;C:\Program Files\nodejs
env PIP_DISABLE_PIP_VERSION_CHECK: 1
env PYTHONIOENCODING: utf-8
env PYTHONPATH: .
env PYTHONHASHSEED: 0
env TOX_ENV_NAME: train
env TOX_WORK_DIR: C:\Users\DELL\Desktop\titanic-assignment\.tox
env TOX_ENV_DIR: C:\Users\DELL\Desktop\titanic-assignment\.tox\test_package
env VIRTUAL_ENV: C:\Users\DELL\Desktop\titanic-assignment\.tox\test_package
env COLUMNS: 165
env LINES: 19
metadata pid: 3672
cwd: C:\Users\DELL\Desktop\titanic-assignment
allow: C:\Users\DELL\Desktop\titanic-assignment\.tox\test_package\Scripts\*
cmd: python classification_model/train_pipeline.py
exit_code: 1

standard error:
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\titanic-assignment\classification_model\train_pipeline.py", line 3, in <module>
    from processing.data_manager import load_dataset, save_pipeline
  File "C:\Users\DELL\Desktop\titanic-assignment\classification_model\processing\data_manager.py", line 8, in <module>
    from classification_model import VERSION as _version
  File "C:\Users\DELL\Desktop\titanic-assignment\classification_model\__init__.py", line 3, in <module>
    from classification_model.config.core import PACKAGE_ROOT, config
  File "C:\Users\DELL\Desktop\titanic-assignment\classification_model\config\core.py", line 99, in <module>
    config = create_and_validate_config()
  File "C:\Users\DELL\Desktop\titanic-assignment\classification_model\config\core.py", line 88, in create_and_validate_config
    parsed_config = fetch_config_from_yaml()
  File "C:\Users\DELL\Desktop\titanic-assignment\classification_model\config\core.py", line 80, in fetch_config_from_yaml
    parsed_config = load(conf_file.read())
  File "C:\Users\DELL\Desktop\titanic-assignment\.tox\test_package\lib\site-packages\strictyaml\parser.py", line 323, in load
    return generic_load(yaml_string, schema=schema, label=label)
  File "C:\Users\DELL\Desktop\titanic-assignment\.tox\test_package\lib\site-packages\strictyaml\parser.py", line 292, in generic_load
    raise parse_error
  File "C:\Users\DELL\Desktop\titanic-assignment\.tox\test_package\lib\site-packages\strictyaml\parser.py", line 285, in generic_load
    document = ruamelyaml.load(yaml_string, Loader=DynamicStrictYAMLLoader)
  File "C:\Users\DELL\Desktop\titanic-assignment\.tox\test_package\lib\site-packages\strictyaml\ruamel\main.py", line 986, in load
    return loader._constructor.get_single_data()
  File "C:\Users\DELL\Desktop\titanic-assignment\.tox\test_package\lib\site-packages\strictyaml\ruamel\constructor.py", line 116, in get_single_data
    return self.construct_document(node)
  File "C:\Users\DELL\Desktop\titanic-assignment\.tox\test_package\lib\site-packages\strictyaml\ruamel\constructor.py", line 126, in construct_document
    for _dummy in generator:
  File "C:\Users\DELL\Desktop\titanic-assignment\.tox\test_package\lib\site-packages\strictyaml\ruamel\constructor.py", line 1645, in construct_yaml_map
    self.construct_mapping(node, data, deep=True)
  File "C:\Users\DELL\Desktop\titanic-assignment\.tox\test_package\lib\site-packages\strictyaml\parser.py", line 101, in construct_mapping
    raise exceptions.DuplicateKeysDisallowed(
strictyaml.exceptions.DuplicateKeysDisallowed: While parsing
  in "<unicode string>", line 6, column 1:
    training_data_file: train.csv
    ^ (line: 6)
Duplicate key 'training_data_file' found
  in "<unicode string>", line 6, column 19:
    training_data_file: train.csv
                      ^ (line: 6)
